name: Build and Push Base Image

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'back-end/seamlessexpressive/seamless-base-image/**'
      - '.github/workflows/build-base-image.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (e.g., cuda12.4-v2)'
        required: false
        default: 'cuda12.4-v1'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: seamless-base

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag || 'cuda12.4-v1' }}
            type=raw,value=latest,enable=${{ github.event.inputs.tag == '' || github.event.inputs.tag == 'cuda12.4-v1' }}
            type=sha,prefix=cuda12.4-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./back-end/seamlessexpressive/seamless-base-image
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Generate summary
        run: |
          echo "## Base Image Build Complete! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Published Images:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n' >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Usage:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`dockerfile" >> $GITHUB_STEP_SUMMARY
          echo "FROM ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag || 'cuda12.4-v1' }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY